apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: multi-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: IfNotPresent # Make sure this is present
        ports:
        - containerPort: 8080
        env:
        - name: API_BASE
          value: "http://api:3000"