apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: multi-tier
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP