apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: logs
          mountPath: /var/log
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: logs
        hostPath:
          path: /var/log